FROM debian:bookworm-slim

ARG TARGETPLATFORM

RUN apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates intel-gpu-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY $TARGETPLATFORM/ugos-exporter /usr/local/bin/ugos-exporter

EXPOSE 9877

ENTRYPOINT ["/usr/local/bin/ugos-exporter"]

